version: '3.8'

services:
  credit-score-service:
    build:
      context: ./credit-score-service
      dockerfile: Dockerfile
    container_name: app-credit-score
    ports:
      - "8082:8080"
    networks:
      - app-network
  credit-score-client:
    build:
      context: ./credit-score-client
      dockerfile: Dockerfile
    container_name: app-soap-client
    ports:
      - "8080:8080"
    depends_on:
      - credit-score-service
    environment:
      - SOAP_SERVICE_URL=http://app-credit-score:8080/services/soap
    networks:
      - app-network
networks:
  app-network:
    driver: bridge